### ISSUE TITLE
[feature]: Reduce the amount of approval dialogs in Metamask by caching approvals

### ISSUE THREAD

**Issue by navFooh** [filecoin-project/filsnap#137]
**Is your feature request related to a problem? Please describe.**
Since updating to `filsnap-adapter` version `1.0.0` and using the official Metamask instead of Flask, we're subject to a lot more approval dialogs in Metamask. Basically when we call `const snap = FilsnapAdapter.connect(...)` and for every subsequent `snap.configure(...)` call, Metamask pops up a dialog to approve the requested path:

<img width="261" alt="image" src="https://github.com/filecoin-project/filsnap/assets/394452/069f2ca6-8e25-442a-b6c9-5c70a7578365">

With Metamask Flask, it seems like the approval was cached so that the user only need to do it once.

**Describe the solution you'd like**
Ideally, approvals should be cached in Metamask so that the user doesn't need to re-approve.

**Describe alternatives you've considered**
After connecting the adapter, we need to configure the snap to derive the address for each account in the user's wallet. We consider caching those derivations in local storage instead of deriving them with the adapter, but it's still not ideal for the user having to approve the same information for each `FilsnapAdapter.connect(...)`, or when switching accounts to sign transactions.

**Comment by ikunal-04** [comment]
Hey @navFooh, can you please explain if I want to contribute to this issue, how I can approach it, and what the prerequisites that I should know? Thank you!!

**Comment by navFooh** [comment]
Hi @ikunal-04, my main focus would be to find out if somethings changed between version `0.3.2` and `1.0.0` that causes a difference in the amount of Metamask approve modals.

When using version `1.0.0` of the snap, they pop up every time when calling `FilsnapAdapter.connect(...)` or `snap.configure(...)`. This didn't happen with version `0.3.2`, so I'd look into what has changed there internally.

I wonder if @hugomrdias or @eshon might know a bit more about this?

**Comment by hugomrdias** [comment]
this is fixed will be in the next release
