### ISSUE TITLE
[bug]: Filsnap adapter fails to connect when multiple wallet providers are installed

### ISSUE THREAD

**Issue by navFooh** [filecoin-project/filsnap#160]
**Describe the bug**
Filsnap does not connect to MetaMask when multiple wallet browser extensions are installed. This seems to be due to the snap communicating with the wrong provider on the `window.ethereum` object. Might be related to missing support for [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963), could help to look at the [mpid](https://github.com/wevm/mipd) package for identifying the right provider.

**To Reproduce**
1. Install other wallet browser extension next to MetaMask (e.g. Rainbow, OKX Wallet)
2. Try to connect FilSnap to MetaMask
3. Connection fails with the error that MetaMask does not support snaps
4. Disable the other browerser extensions and connect again, it works

**Expected behavior**
FilSnap should connect to MetaMask even when multiple wallet providers are installed.

**Comment by eshon** [comment]
[@Montoya ](https://github.com/Montoya) put this together as an official recommendation for Snap teams: 

https://github.com/Montoya/snap-connect-example
