### ISSUE TITLE
Replace `@metamask/snaps-types` with `@metamask/snaps-sdk`

### ISSUE THREAD

**Issue by meandavejustice** [filecoin-project/filsnap#161]
`@metamask/snaps-types` is now superseded by `@metamask/snaps-sdk` 

https://github.com/MetaMask/snaps/blob/7d9c2f4a24dc440c568133a4a5f48bece07595df/packages/examples/packages/get-file/CHANGELOG.md?plain=1#L11C8-L11C27

When this happens, should go through and update all type references throughout snap, adaptor, filsnap-adapter-react etc..

**Comment by Nagu40** [comment]
# Step 1: Update Package
update_package_to("@metamask/snaps-sdk")

# Step 2: Verify Compatibility
if check_compatibility("@metamask/snaps-sdk"):
    proceed_to_next_step()
else:
    handle_incompatibility()

# Step 3: Search and Replace
search_and_replace("@metamask/snaps-types", "@metamask/snaps-sdk")
search_and_replace("@metamask/snaps-ui", "@metamask/snaps-sdk")

# Step 4: Validate Changes
if code_compiles() and code_runs_without_errors():
    continue_with_testing()
else:
    handle_validation_errors()

# Step 5: Thorough Testing
conduct_comprehensive_testing()

# Step 6: Addressing Issues
if issues_encountered():
    investigate_and_resolve_issues()
else:
    proceed_to_documentation_update()

# Step 7: Update Documentation
update_documentation()
