### ISSUE TITLE
[feature]: Prepare Filecoin Wallet screenshots for directory

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filsnap#178]
From MetaMask Snaps team:
> Screenshots are now live on the directory. Please send in your images so we can add them. Here is an example https://snaps.metamask.io/snap/npm/solflare-wallet/solana-snap/
Here are the [guidelines](https://github.com/MetaMask/snaps/discussions/2095).

**Comment by hugomrdias** [comment]
v1.1.0 submission will include screenshots 
![filsnap_1](https://github.com/user-attachments/assets/98ae0e18-0bf5-4a7f-9bc7-0c80f5fa18a6)
![filsnap_2](https://github.com/user-attachments/assets/7391914a-7996-43b6-86be-6cf47f222bc1)
![filsnap_3](https://github.com/user-attachments/assets/b0980142-f4f5-41df-9bfe-b16a745d1c9c)
