### ISSUE TITLE
[feature]: Update to new Transaction Insights version

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filsnap#179]
From MetaMask Snaps team:

> A new version of transaction insights will soon be implemented altering how insights are fetched. You may need to update your Snap logic; please review the [detailed discussion](https://github.com/MetaMask/snaps/discussions/2301).

**Comment by hugomrdias** [comment]
closed by https://github.com/filecoin-project/filsnap/releases/tag/filsnap-v1.3.0

<img width="358" alt="Screenshot 2024-12-30 at 14 38 59" src="https://github.com/user-attachments/assets/d621a3fc-bd67-474b-910f-d491f1d8160e" />
