### ISSUE TITLE
[bug]: Clicking "cancel" in Metamask when connecting results in broken app state

### ISSUE THREAD

**Issue by autonome** [filecoin-project/filsnap#187]
**Describe the bug**

After canceling sign-in in MM, app should handle and reset to initial state.

**To Reproduce**

1. Open fil snap page
2. Click on 'connect'
3. Wait for MM connection panel to load
4. See that you're on testnet
5. Click 'cancel'

**Expected behavior**

The app returns to initial state, with 'connect' button visible and ready to go.

**Actual behavior**

The app shows some funkily-laid-out error text where the 'connect' button should be.

Screenshot:

![CleanShot 2024-04-11 at 10 08 32@2x](https://github.com/filecoin-project/filsnap/assets/50103/ca8da79e-5a2a-41e4-9bd1-1343d0e166b8)

**Comment by kartikey315** [comment]
Hey @autonome, I want to work on this issue can you please guide me.

**Comment by autonome** [comment]
Hi @kartikey315! This is likely not a good starter project. I recommend looking for issues on repos that have `good first bug` tag, etc.

**Comment by kartikey315** [comment]
Okay Thanks. @autonome
