### ISSUE TITLE
[bug]: Should detect switching accounts in MM, and reinitialize app

### ISSUE THREAD

**Issue by autonome** [filecoin-project/filsnap#188]
**Describe the bug**

If I connect to the app with an account, and then in MM switch accounts, the app should reinitialize itself instead of leaving previous-connected account up.

**To Reproduce**

1. Connect to an account
2. Open MM
3. Switch to a different account

**Expected behavior**

The app reinitializes, shows the 'connect' button.

**Actual behavior**

The app does not change, still shows information of previously connected account.

**Comment by hugomrdias** [comment]
Do you mean native or FEVM ? 
Native account are not connected to MM account, it might be a good idea to do that.
FEVM changes when you change account on MM you just need to connect the new account manually

**Comment by autonome** [comment]
I did a round of manual testing today and the demo app behaves differently for different combinations of the flow, and also depending if right after connecting or not.

So I guess fixing this issue would require first to determine whether it's worth shaking out bugs in the demo app, or whether some of this should go in a higher-level library or helper.

Eg, to do this properly, I'd make a matrix of the combinations of the following and have a test which exercises the complete set of valid combinations:

- different networks
- different accounts
- just-connected/already-connected/disconnected

But before writing the test, I bet writing out that matrix would inform whether some API/event/library change might solve the problem better for dapp authors, instead of leaving everything as-is and writing tests for what might be a bucket of footguns.

**Comment by hugomrdias** [comment]
- complete reworked the app to be in sync with the provider (MM and filsnap also stay in sync)
- reconnect on mount is supported now
- MM and filsnap disconnect properly
- Chains are properly added if missing and changed in sync on MM and filsnap

check out https://filsnap.dev
