### ISSUE TITLE
[feature]: Move to entirely static front-end, hosted on GH or Fleek

### ISSUE THREAD

**Issue by autonome** [filecoin-project/filsnap#189]
**Is your feature request related to a problem? Please describe.**

The URL home of the app has already changed once. It's currently hosted on Fission's domain, but they're shutting down.

**Describe the solution you'd like**

The URL home of the app could be Github pages.

Benefits:

- Build trust that the site has not been fucked with (inasmuch as you trust Github)
- Has a pointer to the source code built-in to the URL itself
- Doesn't require whoever is developing it to also be responsible for hosting it

**Describe alternatives you've considered**

We've tried hosting it on the URL of several companies who were paid to develop it, which has resulted in an unstable URL.

**Additional context**

Follow-up issue will be filed for moving to an app-specific domain for DNSlink+IPFS which we can propose to be managed by the Filecoin Foundation.

**Comment by autonome** [comment]
If we fix #190, then maybe Fleek would be better than Github (but introduces another dependency).

**Comment by hugomrdias** [comment]
companion dapp is now deploy from CI to web3.storage and cloudflare pages with ipfs gateway and dnslink support.
