### ISSUE TITLE
[feature]: Move to app-specific domain

### ISSUE THREAD

**Issue by autonome** [filecoin-project/filsnap#190]
**Is your feature request related to a problem? Please describe.**

The front-end is currently hosted via HTTP and IPNS/DNSlink at a Fission.com domain.

Once #189 is fixed, it should move to a new domain that's specific to the app, not a specific company.

**Describe the solution you'd like**

- decide on a domain name
- register it, managed by Filecoin Foundation
- point domain to URL from #189 

**Describe alternatives you've considered**

We tried domains of the companies who were leading development at the time, but that changes.

**Comment by hugomrdias** [comment]
companion dapp is now on the filsnap.dev domain
