### ISSUE TITLE
Error while running snap 'npm:@chainsafe/filsnap': Cannot add property default, object is not extensible

### ISSUE THREAD

**Issue by utgarda** [filecoin-project/filsnap#2]
https://filsnap.chainsafe.io/
Pressing "connect to metamask" button results in 
```
inpage.js:1 MetaMask - RPC Error: Error while running snap 'npm:@chainsafe/filsnap': Cannot add property default, object is not extensible 
```
MetaMask Version
10.31.0-flask.0

Chrome logo
Google Chrome
Version 113.0.5672.92 (Official Build) (64-bit)

Tried the same on newer everything, same result
![image](https://github.com/filecoin-project/filsnap/assets/15115/5eae6580-caa9-44c8-b166-bfe0de8b0d6b)

**Comment by hugomrdias** [comment]
There a new demo app https://filsnap.fission.app/ and npm package `filsnap`
