### ISSUE TITLE
FVM Transaction Support

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filsnap#8]
As mentioned in https://github.com/filecoin-project/filsnap/issues/1 support for the following FVM transactions is needed, as confirmed by @honghaoq from the FVM Product team:

Top priority:
- Send from f1 to 0x/f410
- Send from 0x/f410 to f1

The above would help resolve current issues from users trying to send to/from FEVM wallets and Coinbase, which currently requires complex workarounds using a Glif Burner Wallet or FilForwarder contract.

Question:
- Will the seed phrase for a native f1 and 0x/f410 wallet be the same? 
    - (i.e., do they have different derivation paths/SLIP-0044 using the same seed?)

Related features to support:

- Create a new 0x/f410 account
- Export keys from 0x/f410 account
- Import keys from existing 0x/f410 account
- Use Filecoin Eth JSON RPC
- Gas for Eth JSON RPC Tx's
- Ledger support for 0x/f410 and f1??

**Comment by raulk** [comment]
f410 senders are Ethereum accounts, which use the Ethereum RLP-encoded message and Ethereum signature scheme in Filecoin as mandated by the Ethereum protocol and produced by Ethereum wallets. This signature scheme assumes a 20-byte encoded recipient address. Thus, we cannot use an f1 address directly as the full address size is 21 bytes (protocol + payload). We can't elide the protocol byte as it would lead to ambiguity in address spaces (mixing up f410 and f1).

**Comment by eshon** [comment]
Note that the STFIL staking team are also interested in adding support for sending funds from an f1 account to an FEVM smart contract to support their staking use case and have proposed a PR here: https://github.com/filecoin-project/filsnap/pull/22

**Comment by hugomrdias** [comment]
@eshon can we close this one ?
