### ISSUE TITLE
"Add FEVM Mainnet" button doesn't appear to do anything

### ISSUE THREAD

**Issue by meandavejustice** [filecoin-project/filsnap#86]
This is on local dev, master at https://github.com/filecoin-project/filsnap/commit/f0a8e4c875cdcd880665fd156397f393d599ee1b

![filsnap-add-fevm-button-doesnt-do-anything](https://github.com/filecoin-project/filsnap/assets/1844554/f625cc60-e5e3-4441-b381-d41bb82eabb1)

**Comment by hugomrdias** [comment]
this is a helper method if the network is already added to metamask it will do nothing. 
Try removing all filecoin networks and click the button again
